@echo off
echo Adding all files...
git add -A
echo Committing changes...
git commit -m "Fix build by adding terser dependency and using esbuild for minification"
echo Pushing to GitHub...
git push
echo Done! 