name = "khochuan-pos-api"
main = "src/index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
API_VERSION = "v1"
NODE_ENV = "production"
CORS_ORIGIN = "https://khochuan-pos.pages.dev"
JWT_SECRET = "cloudflare-khochuan-pos-jwt-secret-key-2025"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "khochuan-pos-db"
database_id = "khochuan-pos-db-id"

# KV Namespace binding for caching
[[kv_namespaces]]
binding = "CACHE"
id = "khochuan-pos-cache-id"
preview_id = "khochuan-pos-cache-preview-id"

# R2 Storage for file uploads
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "khochuan-pos-storage"
preview_bucket_name = "khochuan-pos-storage-preview"