const fs = require('fs');
const path = require('path');

// Simple 1x1 pixel PNG data (blue color)
const pngData192 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAACXBIWXMAAAsTAAALEwEAmpwYAAABNklEQVR4nO3VsQnAQAwEQffff+fKwQQTTDBwM3BVSPvMzLwA6b0PANYIADQBAEYAoAkAMAIATQCAEQBoAgCMAEATAGAEAJoAACMA0AQAGAGAJgDACAAcM/NbvQH4nQBAEwBgBACaAAAjANAEABgBgCYAwAgANAEARgCgCQAwAgBNAIARAGgCAIwAQBMAYAQAmgAAIwDQBAAYAYAmAMAIADQBAEYAoAkAMAIATQCAEQBoAgCMAEATAGAEAJoAACMA0AQAGAGAJgDACAAcM/NbvQH4nQBAEwBgBACaAAAjANAEABgBgCYAwAgANAEARgCgCQAwAgBNAIARAGgCAIwAQBMAYAQAmgAAIwDQBAAYAYAmAMAIADQBAEYAoAkAMAIATQCAEQBoAgCMAEATAGAEAJoAACMA0AQAmADA8QDzogSAhFgWoQAAAABJRU5ErkJggg==', 'base64');

const pngData512 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAAsTAAALEwEAmpwYAAABNklEQVR4nO3VsQnAQAwEQffff+fKwQQTTDBwM3BVSPvMzLwA6b0PANYIADQBAEYAoAkAMAIATQCAEQBoAgCMAEATAGAEAJoAACMA0AQAGAGAJgDACAAcM/NbvQH4nQBAEwBgBACaAAAjANAEABgBgCYAwAgANAEARgCgCQAwAgBNAIARAGgCAIwAQBMAYAQAmgAAIwDQBAAYAYAmAMAIADQBAEYAoAkAMAIATQCAEQBoAgCMAEATAGAEAJoAACMA0AQAGAGAJgDACAAcM/NbvQH4nQBAEwBgBACaAAAjANAEABgBgCYAwAgANAEARgCgCQAwAgBNAIARAGgCAIwAQBMAYAQAmgAAIwDQBAAYAYAmAMAIADQBAEYAoAkAMAIATQCAEQBoAgCMAEATAGAEAJoAACMA0AQAmADA8QDzogSAhFgWoQAAAABJRU5ErkJggg==', 'base64');

// Create the icons directory if it doesn't exist
const iconsDir = path.join(__dirname, '../frontend/public/icons');
if (!fs.existsSync(iconsDir)) {
  fs.mkdirSync(iconsDir, { recursive: true });
}

// Write the PNG files
fs.writeFileSync(path.join(iconsDir, 'icon-192x192.png'), pngData192);
fs.writeFileSync(path.join(iconsDir, 'icon-512x512.png'), pngData512);

console.log('Icons generated successfully!'); 